project:
  type: website
  output-dir: "docs"

website:
  title: "Olaitan Elihou Adje"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
format:
  html:
    theme: morph
    css: styles.css

editor: source